
services:
  postgres:
    image: postgres:15
    container_name: store_navigator_db
    environment:
      POSTGRES_DB: store_navigator
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: store_navigator_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: